api: 
  url: https://apptwo.contrastsecurity.com/Contrast
  api_key: V2L516LQEYOe4bCP50jJWftue1wn8TZf
  service_key: 38PRUFWWXANI9OGH
  user_name: agent_6119fcd6-5a74-48e8-aff8-092520138ef3@AcmeInc
agent: 
  service: 
    logger: 
      path: contrast_service.log
      level: ERROR
    host: 127.0.0.1
    port: 30555
application: 
  name: FirstAppTest
